clone:
  git:
    image: plugins/git
    tags: true

workspace:
  base: /go
  path: src/github.com/naveego/plugin-odbc

matrix:
  GOOS:
    - linux
    - windows
    - darwin

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - vendor
    volumes:
      - /tmp/cache:/cache

  build:
    image: docker.naveego.com:4333/build-go:latest
    pull: true
    environment:
      - CGO_ENABLED=0
      - GOOS=${GOOS}
    commands:
      - dep ensure -vendor-only
      - go build -o plugin-odbc

  publish-test:
    image: docker.naveego.com:4333/navget-drone:latest
    pull: true
    endpoint: http://navget.n5o.green
    files: plugin-odbc icon.png
    os: ${GOOS}
    secrets: ["navget_token"]
    when:
      branch: master

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - vendor
    volumes:
      - /tmp/cache:/cache
    when:
      status: [failure, success]
