version: "2.0"

services:
  sql:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - 1433:1433
      - 1434:1434
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: n5o_ADMIN
    logging:
      driver: json-file




